#!/usr/bin/env node

import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(dirname(fileURLToPath(import.meta.url))));
const sourceDir = join(rootDir, "frontend", "src", "cases", "task-board", "source");
const outputFile = join(rootDir, "frontend", "src", "cases", "task-board", "generatedFiles.ts");

const sourceFiles = await collectFiles(sourceDir);
const files = {};
for (const sourceFile of sourceFiles) {
  const relativePath = relative(sourceDir, sourceFile).replaceAll("\\", "/");
  const content = await readFile(sourceFile, "utf8");
  if (content.length === 0) {
    throw new Error(`任务看板源文件为空：${relativePath}`);
  }
  files[`/${relativePath}`] = content.replaceAll("\r\n", "\n");
}

const serialized = `/* Generated by scripts/assembleTaskBoardCase.mjs from frontend/src/cases/task-board/source. */\nexport const TASK_BOARD_CASE_FILES = ${JSON.stringify(files, null, 2)} as const;\n`;
if (process.argv.includes("--check")) {
  const current = await readFile(outputFile, "utf8");
  if (current !== serialized) {
    throw new Error("任务看板 generatedFiles.ts 不是由当前 source 生成，请运行 node scripts/assembleTaskBoardCase.mjs");
  }
} else {
  await writeFile(outputFile, serialized, "utf8");
}

console.log(`Task board case map ${process.argv.includes("--check") ? "is current" : "generated"}: ${sourceFiles.length} files`);

async function collectFiles(directory) {
  const entries = (await readdir(directory, { withFileTypes: true }))
    .filter((entry) => entry.name !== "node_modules")
    .sort((first, second) => first.name.localeCompare(second.name));
  const nested = await Promise.all(entries.map(async (entry) => {
    const entryPath = join(directory, entry.name);
    return entry.isDirectory() ? collectFiles(entryPath) : [entryPath];
  }));
  return nested.flat().sort();
}
