#!/usr/bin/env node

import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const caseId = process.argv.slice(2).find((value) => value.startsWith("--case="))?.slice("--case=".length);
const allowed = new Set(["customer-management", "analytics-dashboard", "personal-blog"]);
if (caseId === undefined || !allowed.has(caseId)) throw new Error("请通过 --case=customer-management|analytics-dashboard|personal-blog 指定案例");
const sourceDir = join(rootDir, "frontend", "src", "cases", caseId, "source");
const outputFile = join(rootDir, "frontend", "src", "cases", caseId, "generatedFiles.ts");
const files = {};
for (const sourceFile of await collectFiles(sourceDir)) {
  const relativePath = relative(sourceDir, sourceFile).replaceAll("\\", "/");
  const content = await readFile(sourceFile, "utf8");
  if (content.length === 0) throw new Error(`案例源文件为空：${relativePath}`);
  files[`/${relativePath}`] = content.replaceAll("\r\n", "\n");
}
const constant = caseId.replaceAll("-", "_").toUpperCase() + "_CASE_FILES";
const serialized = `/* Generated by scripts/assembleWorkspaceDemoCase.mjs from frontend/src/cases/${caseId}/source. */\nexport const ${constant} = ${JSON.stringify(files, null, 2)} as const;\n`;
if (process.argv.includes("--check")) {
  const current = await readFile(outputFile, "utf8");
  if (current !== serialized) throw new Error(`${caseId} generatedFiles.ts 不是由当前 source 生成`);
} else {
  await writeFile(outputFile, serialized, "utf8");
}
console.log(`${caseId} case map ${process.argv.includes("--check") ? "is current" : "generated"}: ${Object.keys(files).length} files`);

async function collectFiles(directory) {
  const entries = (await readdir(directory, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name));
  const nested = await Promise.all(entries.map(async (entry) => {
    const entryPath = join(directory, entry.name);
    return entry.isDirectory() ? collectFiles(entryPath) : [entryPath];
  }));
  return nested.flat().sort();
}
